[tool.poetry]
name = "django-jovo-client"
version = "0.1.0"
description = ""
authors = ["gaurav <gaurav@jovo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.7"
django-tailwind = {version = "^4.2.0", extras = ["reload"]}
django-cotton = "^2.1.3"
mysqlclient = "^2.2.7"
sqlalchemy = "^2.0.44"
pymysql = "^1.1.2"
psycopg2-binary = "^2.9.11"
oracledb = "^3.4.0"
python-dotenv = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
